AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  focusmode
  SAM Template for Santa Clara University's HCI Lab's FocusMode project

Parameters:
  OpenAIKey:
    Type: String
    Description: API Key for OpenAI
    Default: abc
  YouTubeApiKey:
    Type: String
    Description: API Key for youtube
    Default: abc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        OpenAIKey: !Ref OpenAIKey
        YouTubeApiKey: !Ref YouTubeApiKey
        UserTableName: !Ref FocusModeUserTable
        DataTableName: !Ref FocusModeDataCollectionTable
        DailySurveyDataTableName: !Ref FocusModeDailySurveyResponseTable
        PostStageSurveyDataTableName: !Ref FocusModePostStageSurveyResponseTable
        UserPreferenceDataTableName: !Ref FocusModeUserPreferenceDataTable
        AdminTableName: !Ref FocusModeAdminTable
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowHeaders: '''Content-Type'''
      AllowMethods: '''GET'''

Resources:
  FocusModeApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: FocusMode Api Gateway
      StageName: Prod
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type'''
        AllowMethods: '''GET'''

  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: utils_layer
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  CategorizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: categorize/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilsLayer
      Events:
        CategorizeApi:
          Type: Api
          Properties:
            RestApiId: !Ref FocusModeApiGateway
            Path: /categorize
            Method: ANY
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeDataCollectionTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeDailySurveyResponseTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModePostStageSurveyResponseTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeUserPreferenceDataTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeAdminTable

  CollectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: collect/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilsLayer
      Events:
        CategorizeApi:
          Type: Api
          Properties:
            RestApiId: !Ref FocusModeApiGateway
            Path: /collect
            Method: ANY
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeDataCollectionTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeDailySurveyResponseTable
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModePostStageSurveyResponseTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeAdminTable

  OnboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onboard/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilsLayer
      Events:
        CategorizeApi:
          Type: Api
          Properties:
            RestApiId: !Ref FocusModeApiGateway
            Path: /onboard
            Method: ANY
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeAdminTable

  StageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stage/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilsLayer
      Events:
        CategorizeApi:
          Type: Api
          Properties:
            RestApiId: !Ref FocusModeApiGateway
            Path: /stage
            Method: ANY
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeUserTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeDataCollectionTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeDailySurveyResponseTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModePostStageSurveyResponseTable
        - DynamoDBReadPolicy:
            TableName: !Ref FocusModeAdminTable

  FocusModeUserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: User_Id
        Type: String

  FocusModeDataCollectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: User_Id
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: User_Id
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FocusModeDailySurveyResponseTable:
  Type: AWS::DynamoDB::Table
  Properties:
    KeySchema:
      - AttributeName: prolificId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: prolificId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
    BillingMode: PROVISIONED
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

  FocusModePostStageSurveyResponseTable:
  Type: AWS::DynamoDB::Table
  Properties:
    KeySchema:
      - AttributeName: prolificId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: prolificId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
    BillingMode: PROVISIONED
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

  FocusModeUserPreferenceDataTable:
  Type: AWS::DynamoDB::Table
  Properties:
    KeySchema:
      - AttributeName: prolificId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: prolificId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
    BillingMode: PROVISIONED
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

  FocusModeAdminTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  FocusModeApiGateway:
    Description: API Gateway endpoint URL for Prod stage for lambda functions
    Value: !Sub https://${FocusModeApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/categorize/
  FocusModeApiGatewayRestApiId:
    Description: API Gateway ARN for AWS API Gateway
    Value: !Ref FocusModeApiGateway
    Export:
      Name: FocusModeApiGateway-RestApiId
  FocusModeApiGatewayRootResourceId:
    Value: !GetAtt FocusModeApiGateway.RootResourceId
    Export:
      Name: FocusModeApiGateway-RootResourceId
  UtilsLayerArn:
    Description: Layer for utils
    Value: !Ref UtilsLayer
    Export:
      Name: !Sub ${AWS::StackName}-UtilsLayerArn
  # CategorizeApi:
  #   Description: API Gateway endpoint URL for Prod stage for Categorize function
  #   Value: !Sub "https://${FocusModeApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/categorize/"
  # CategorizeFunction:
  #   Description: Categorize Lambda Function ARN
  #   Value: !GetAtt CategorizeFunction.Arn
  # CategorizeFunctionIamRole:
  #   Description: Implicit IAM Role created for Categorize function
  #   Value: !GetAtt CategorizeFunctionRole.Arn